import { AdminState } from '../constants/states.constant';

const AUTHENTICATED_ADMIN_STATES = new Set<string>([
    AdminState.AUTHENTICATED,
    AdminState.AUTHENTICATED_WITH_WAREHOUSE,
    AdminState.CHANGE_PASSWORD_AWAITING_NEW,
    AdminState.SET_WAREHOUSE_SELECTING,
    AdminState.CREATE_WAREHOUSE_AWAITING_NAME,
    AdminState.CREATE_WAREHOUSE_AWAITING_ADDRESS,
    AdminState.EDIT_WAREHOUSES_SELECTING,
    AdminState.EDIT_WAREHOUSE_ACTION_SELECTING,
    AdminState.EDIT_WAREHOUSE_AWAITING_NAME,
    AdminState.EDIT_WAREHOUSE_AWAITING_ADDRESS,
    AdminState.EDIT_WAREHOUSE_AWAITING_STATUS,
    AdminState.EDIT_WAREHOUSE_AWAITING_DELETE_CONFIRM,
    AdminState.EDIT_ADMINS_SELECTING,
    AdminState.EDIT_ADMIN_ACTION_SELECTING,
    AdminState.EDIT_ADMIN_AWAITING_STATUS,
    AdminState.EDIT_ADMIN_AWAITING_DELETE_CONFIRM,
    AdminState.EDIT_ADMIN_AWAITING_PASSWORD,
    AdminState.APPLY_REGISTRATIONS_SELECTING,
    AdminState.APPLY_REGISTRATION_AWAITING_CONFIRM,
    AdminState.ADMIN_SESSIONS_HISTORY_AWAITING_DATE,
    AdminState.ADD_SIM_AWAITING_NUMBER,
    AdminState.SIM_INTERACTIONS_SELECTING,
    AdminState.SIM_INTERACTION_ACTION_SELECTING,
    AdminState.SIM_INTERACTION_AWAITING_ACTIVE_STATUS,
    AdminState.SIM_INTERACTION_AWAITING_CONDITION_STATUS,
    AdminState.SIM_INTERACTION_AWAITING_DELETE_CONFIRM,
    AdminState.ADMIN_EDIT_COURIERS_SELECTING,
    AdminState.SUPERADMIN_EDIT_COURIERS_SELECTING,
    AdminState.ADMIN_EDIT_COURIER_ACTION_SELECTING,
    AdminState.SUPERADMIN_EDIT_COURIER_ACTION_SELECTING,
    AdminState.ADMIN_EDIT_COURIER_AWAITING_STATUS,
    AdminState.SUPERADMIN_EDIT_COURIER_AWAITING_STATUS,
    AdminState.ADMIN_COURIER_HISTORY_AWAITING_FULL,
    AdminState.SUPERADMIN_COURIER_HISTORY_AWAITING_FULL
]);

/** Проверяет, что состояние относится к авторизованному admin subflow. */
export function isInAuthenticatedOrSubflow(currentState?: string): boolean {
    if (!currentState) {
        return false;
    }

    return AUTHENTICATED_ADMIN_STATES.has(currentState);
}
